Add remove
marilirulita/ToDoList pull request #2
Opened 2022-01-12 21:54 UTC by marilirulita

add functions add and remove elements
update list array in local store
add edit elements function

2022-01-12 22:44 UTC, MrBrN197 requested changes
## Hi, @marilirulita  👋 

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!
## To highlight 👏👏
- ✔ javascript is functioning well

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 22:44 UTC, MrBrN197 commented on src/addElement.js
> +/* eslint-disable import/no-cycle */
- [ ] Please avoid using `eslint-disable` to get around ESlint errors. ESlint errors are usually denoting an underlying problem with the way your code is setup up. please remove this ESLint error and address any issues that you may have. I know it's much easier to just disable these errors but it's much better to learn to write clean code.

2022-01-12 22:44 UTC, MrBrN197 commented on src/deleteElements.js
> +/* eslint-disable import/no-cycle */
- [ ] Please fix this ESlint issue as mentioned in my comment above.

2022-01-12 22:44 UTC, MrBrN197 commented on src/display.js
> +/* eslint-disable import/no-cycle */
- [ ] Please fix this ESlint issue as mentioned in my comment above.

2022-01-12 22:44 UTC, MrBrN197 commented on src/editTask.js
> +/* eslint-disable import/no-cycle */
- [ ] Please fix this ESlint issue as mentioned in my comment above.

2022-01-13 00:36 UTC, Cathella approved these changes
## 🟩  Status: Approved 🎉💪🏻

### Hi @marilirulita 👋🏻, 

You did a tremendous job implementing the requested changes 💪🏻.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 17:47 UTC, merged